// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Infrastructure.Data;

#nullable disable

namespace Tracker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Tracker.Domain.Entities.Analysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsTestData");

                    b.HasIndex("ResumeId");

                    b.HasIndex("JobId", "ResumeId", "CreatedAt");

                    b.ToTable("analyses", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.AnalysisRequestMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<bool>("CacheHit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsedGapLlmFallback")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CacheHit");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobHash");

                    b.HasIndex("RequestMode");

                    b.ToTable("analysis_request_metrics", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoverageScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GroundednessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingPreferredJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingRequiredJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSkillsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryAlignmentNote")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaryAlignmentScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("AnalysisId");

                    b.ToTable("analysis_results", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<decimal>("AvgCostPerRunUsd")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AvgLatencyMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CoverageStabilityDiff")
                        .HasPrecision(8, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GroundednessRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PassedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SchemaPassRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("eval_runs", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCareersUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecruiterEmail")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecruiterLinkedIn")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecruiterName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecruiterPhone")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DescriptionHash");

                    b.HasIndex("IsTestData");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("ApplicationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsTestData");

                    b.HasIndex("JobId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("Status");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.JobApplicationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Channel")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PositiveOutcome")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventAt");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("job_application_events", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.LlmLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<Guid>("AnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ParseSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawResponse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RepairAttempted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("llm_logs", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesiredSalaryMax")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DesiredSalaryMin")
                        .HasPrecision(12, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTestData")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsTestData");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Analysis", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Job", "Job")
                        .WithMany("Analyses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Domain.Entities.Resume", "Resume")
                        .WithMany("Analyses")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.AnalysisResult", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Analysis", "Analysis")
                        .WithOne("Result")
                        .HasForeignKey("Tracker.Domain.Entities.AnalysisResult", "AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tracker.Domain.Entities.Resume", "Resume")
                        .WithMany("Applications")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.JobApplicationEvent", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.JobApplication", "JobApplication")
                        .WithMany("Events")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.LlmLog", b =>
                {
                    b.HasOne("Tracker.Domain.Entities.Analysis", "Analysis")
                        .WithMany("Logs")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Analysis", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Result");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Job", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.JobApplication", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Tracker.Domain.Entities.Resume", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
